services:
  flare:
    build: .
    image: flare-dht
    command: ["server", "-l", "-p", "80"]
    ports:
      - 8001:80
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G