[package]
name = "flare-dht"
description = "The learning project to create the distributed KV database in Rust language."
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
"default" = ["cluster"]
"cluster" = []

[dependencies]
dashmap = "6.1"
mur3 = "0.1"
tonic = {workspace=true}
tonic-reflection = { version = "0.12", features = ["server"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "net"] }
openraft = { version = "0.9", features = ["serde", "storage-v2"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = "4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rkyv = { version = "0.8", features = ["alloc"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
thiserror = "1.0"
rancor = "0.1.0"
rand = "0.8"
tsid = "0.3"
flare-pb = {workspace=true}
async-trait = "0.1"
tokio-stream = { version = "0.1", features = ["sync"] }
http = "1.1"
bytes={version = "1.7", features = []}
hashbrown = "0.14.5"
mobc = "0.8.4"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["async_futures", "async_tokio", "html_reports", "tokio"] }

[[bench]]
name = "write_benchmark"
harness = false

[profile.release]
lto = true
codegen-units = 1
